services:
  backend:
    build: ./backend
    container_name: express-backend
    labels:
      app: todo-app
      role: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8000
      - HOST=0.0.0.0
    networks:
      - app-network
    command: nodemon --watch . --legacy-watch index.js
    healthcheck:
      test:
        ["CMD-SHELL", "wget --spider -q http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  frontend:
    build: ./frontend
    container_name: react-frontend
    labels:
      app: todo-app
      role: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_PORT=5173
      - VITE_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    networks:
      - app-network
    command: npm run dev -- --host --port 5173
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:5173/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  db:
    image: mongo:6.0
    container_name: mongo-db
    labels:
      app: todo-app
      role: db
    environment:
      MONGO_DATABASE: todo_app_db
      MONGO_USER: hamid
      MONGO_PASSWORD: Hamid.123
      MONGO_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - todo-app-db-data:/var/lib/mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  todo-app-db-data:
